### ISSUE TITLE
Add/mention option for UTF nbsps in Readme

### ISSUE THREAD

**Issue by kizu** [sapegin/richtypo.js#11]
I tried the example from the readme and thought it didn't work, as the output had UTF nbsps — ` `, but Readme had escaped HTML ones — `&nbsp;`.

Is there an option for setting the output to html-escaped one? If not, then it should be mentioned in Readme, so people won't confuse when they won't see the escaped nbsps in their result.

**Comment by algenon** [comment]
IMO, using `&nbsp;` would be much clearer than the non-breaking space itself. Otherwise, it causes confusion. The doc says that:

```javascript
var beautiful = richtypo.rich('Welcome to the world');
```

Will produce something like that:

```html
Welcome to&nbsp;the world
```

But actually it does not produce `&nbsp;`, so it looks like the library is not working.

**Comment by sapegin** [comment]
Yeah, docs could be better. But there’s really no point (except for debugging purposes) in generating actual `&nbsp;`s instead of non-breaking spaces.

Anyway docs improvements or PRs/suggestions on how I can improve the library are welcomed.

**Comment by algenon** [comment]
Ease of debugging and testing are valid reasons by themselves, why not consider them? Sure, `&nbsp;` is 5 characters longer and less readable, but who cares anyway. The raw output is not for human to read.

**Comment by sapegin** [comment]
Closing this issue in favor of #13.
