### ISSUE TITLE
Ability to insert HTML entities instead of Unicode 

### ISSUE THREAD

**Issue by sapegin** [sapegin/richtypo.js#13]
As discussed in #11.

I see to ways of doing it:

**First**. Add new ruleset and use it like this:

```
richtypo.richtypo('Welcome to out website!', […, 'replace_entities', …], 'en');
```

It’s easy to implement but difficult to use.

**Second**. Add configuration method:

```
richtypo. setOptions({
  html_entities: true
})
```

Requires more work but much easier to use. And we could add more options later.

P. S. It’s probably better to add an option not only for `&nbsp;`s but for any special character: quotes, dashes, etc.

@algenon, @kizu what do you think?

**Comment by algenon** [comment]
Second method definitely looks better for me. Great idea to use a broader scope option (`html_entities`), not only nbsps.

**Comment by sapegin** [comment]
I thinks it’s better to use a separate library for that, like [he](https://github.com/mathiasbynens/he), so I’m going to close this for now.
