### ISSUE TITLE
Undo function (duplicate <abbr> and <nobr> on already typographed text)

### ISSUE THREAD

**Issue by algenon** [sapegin/richtypo.js#15]
Richtypo is not idempotent. E.g., if you process text which already has abbreviated (via `<abbr>`) words, then `<abbr>` tags are duplicated:

``` javascript
expect(rt.title('<abbr>WWW</abbr>'))
  .toBe(_symb('<abbr>WWW</abbr>'));
// actual: '<abbr><abbr>WWW</abbr></abbr>'
```

Not sure if you consider it a bug, maybe the library is intended to work this way. I'd certainly prefer it to not duplicate existing `abbr`s and `nobr`s.

Maybe preservе content for these tags "as is", like `code` or `pre`? Probably if someone is using `nobr` in his text, he already took care of typography inside it.

**Comment by sapegin** [comment]
It’s a tough question :-)

1. It’s better to run Richtypo at output stage and not store typographed text back to source files / database.

2. It’s hard to automate such checks. What if I purposefully wrap some elements in `<abbr>` or `<nobr>` tags?

I think the best option is to implement `richtypo.undo` function that will remove all possible typography stuff: non-breaking spaces, `<abbr>`s and `<nobr>`s, etc.

**Comment by algenon** [comment]
Interesting idea with `undo`, may do the job. Anyway, I believe you can safely ignore this improvement as it is only a theoretical concern, not really bothering someone.
