### ISSUE TITLE
Richtypo adds &nbsp; between line break and em dash

### ISSUE THREAD

**Issue by arturi** [sapegin/richtypo.js#17]
<img width="768" alt="screen shot 2015-09-22 at 23 28 43" src="https://cloud.githubusercontent.com/assets/1199054/10030720/e1ce8bb8-6181-11e5-9a25-269aeadc4250.png">

**Comment by sapegin** [comment]
Can you share the source text somewhere?

**Comment by arturi** [comment]
```
![image](/media/copenhagen-berlin/IMG_9266.jpg)

— Сколько нужно хипстеров, чтобы заготовить дрова?
— Два: один будет рубить, второй красиво укладывать.

![image](/media/copenhagen-berlin/IMG_9232.jpg)
```

After it gets parsed with Markdown, ```<br>``` is added here:
```
— Сколько нужно хипстеров, чтобы заготовить дрова?<br>
— Два: один будет рубить, второй красиво укладывать.
```

**Comment by arturi** [comment]
https://tonicdev.com/5600613fea18ef0d00d46316/5601bd6590f17b0d00a7cb0f

**Comment by sapegin** [comment]
Works fine with a correct Markdown:

```
— Сколько нужно хипстеров, чтобы — заготовить дрова?\n\n— Два: один будет рубить, второй красиво укладывать.
```

**Comment by arturi** [comment]
But I don’t need a new paragraph for every line, it has to be a line break here.

**Comment by arturi** [comment]
Made a suggestion on how to fix here: https://github.com/sapegin/richtypo.js/compare/master...arturi:patch-1. This fixes an issue for me. What do you think?
