### ISSUE TITLE
Time to cut a new release?

### ISSUE THREAD

**Issue by bobthecow** [sapegin/richtypo.js#21]
In addition to making awesome new feature and fixes available (I guess I'm a bit biased), this would fix #18 :)

**Comment by sapegin** [comment]
I’m updating the example, and the I’ll make a new release.

**Comment by bobthecow** [comment]
Great, thanks! :)

**Comment by sapegin** [comment]
Done ;-)

**Comment by bobthecow** [comment]
:+1:
