### ISSUE TITLE
Take care of orphans

### ISSUE THREAD

**Issue by kizu** [sapegin/richtypo.js#3]
From [wiki](http://en.wikipedia.org/wiki/Widows_and_orphans):

> A word […] that appears by itself at the end of a paragraph. Orphans result in too much white space between paragraphs or at the bottom of a page.

It could be nice to take care of orphans at the end of different block-level elements like paragraphs, headers, list items etc.

The rule would be rather simple: there should be a nbsp between the last two words at the end of each block-level element.

We should look not at the words only, but also for the wanted length of the last line in symbols, so if there would be a very long word or a few very short words, then there would be either no nbsps inserted, either more that one.

**Comment by bobthecow** [comment]
:+1:
