### ISSUE TITLE
WebKit error on markdown fenced code blocks regex

### ISSUE THREAD

**Issue by Grawl** [sapegin/richtypo.js#34]
`SyntaxError: Invalid regular expression: invalid group specifier name`

This code:

`/(?<=\])\([^)]+\)/gim, // Markdown fenced code blocks`

**Comment by sapegin** [comment]
Are you trying to run it in the browser?

**Comment by Grawl** [comment]
Yes. It's small and fast, why not

**Comment by sapegin** [comment]
Looks like Safari is [the only browser that doesn't support lookbehinds](https://caniuse.com/#feat=js-regexp-lookbehind) in regular expressions, which is unfortunate — I think we use it quite a lot now.

You can try to use 3.x — it should work in the browser but has a different API.
