### ISSUE TITLE
Keep consecutive spaces

### ISSUE THREAD

**Issue by lukashavrlant** [sapegin/richtypo.js#39]
I tried to use richtypo to enrich my text but it keeps removing consecutive spaces which I do not want. Hence I am not able to write code examples in my text or other text that depends on indentation. I believe this test should pass: 

```js
it('should keep repeating consecutive spaces', () => {
    const input = 'function () {\n    console.log(1);\n}';
    expect(richtypo([], input)).to.be.equal(input);
});
```

But it fails because [it always executes `beforeAll` rule](https://github.com/sapegin/richtypo.js/blob/master/packages/richtypo/src/richtypo.js#L22) which removes repeating spaces. Can it be configured somehow to not remove repeating spaces?

**Comment by sapegin** [comment]
It's weird that you run it on code, not natural text. Not sure what you're trying to achieve with that.

**Comment by lukashavrlant** [comment]
@sapegin It's an article containing code examples.

**Comment by sapegin** [comment]
I don't know what you're using to write it but Richtypo supports code examples in HTML and Markdown, not in plain text.
