### ISSUE TITLE
Work with markdown documents

### ISSUE THREAD

**Issue by kizu** [sapegin/richtypo.js#5]
If we are using richtypo (via CLI or maybe using an option) for files in markdown format (`.md` etc.) then richtypo would need to know what _not_ to enhance, because right now there would be a lot of errors and richtypo would destroy the markup in most of the cases.

Here are some of the basic examples, and there could be a lot of them (some of them are not markdown specific, so those could be fixed in general, but whatever):
- [ ] markdown's `<hr>`s made as `---` etc. on a single line now transform to `—`;
- [ ] hanging typography is applied to the markup like `![](blah)` transforming them to `![]<span class="hbrace">(</span>blah)`;
- [ ] dashes that start the lists are transformed to the `&mdash;`;
- [ ] indentations are not preserved: if there were more that one spaces at the beginning of the line, then after the convertation there would be only one;
- [ ] text in code blocks (ah, that wouldn't be easy to parse…) shouldn't be typographed, 'cause the actual symbols there should be exact as you write them;

**Comment by sapegin** [comment]
I’m going to close this for now — it sounds like a nice feature but out of scope of this package and most likely will never be implemented (this issue is four-year-old ;–)
